### ISSUE TITLE
Auto Aiming of Shooter and DriveTrain using AprilTag Tracking From LimeLight

### ISSUE THREAD

**Issue by dlezcan1** [BLlakers/2024_Official#15]
- [ ] Calibrate Limelight pose relative to robot
- [ ] Validate accurate angle measurement from shooter
- [ ] Update minimum, optimal, and maximum distances for april tag alignment
- [ ] Bind AutoShoot command to button
- [ ] Test AutoShoot command
- [ ] Determine optimal angles to shoot at based on distance
